### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.ops'

### ISSUE THREAD

**Issue by landian60** [ducminhkhoi/Amodal-Instance-Seg-ASBU#1]
Hello! The "mmdet" module which should be installed is not written in the "requirements.txt".And I install it but it occurs error that I can not solve it. Could you tell me what version of your "mmcv" and "mmdet" module? Thank you.
The log:
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from trainer import Trainer
  File "/home/user15/Amodal-Instance-Seg-ASBU/trainer.py", line 12, in <module>
    import models
  File "/home/user15/Amodal-Instance-Seg-ASBU/models/__init__.py", line 1, in <module>
    from . import backbone
  File "/home/user15/Amodal-Instance-Seg-ASBU/models/backbone/__init__.py", line 1, in <module>
    from .unet import *
  File "/home/user15/Amodal-Instance-Seg-ASBU/models/backbone/unet/__init__.py", line 1, in <module>
    from .unet_model import *
  File "/home/user15/Amodal-Instance-Seg-ASBU/models/backbone/unet/unet_model.py", line 8, in <module>
    from mmdet.ops.dcn.deform_conv import ModulatedDeformConvPack as Deform
ModuleNotFoundError: No module named 'mmdet.ops'
Killing subprocess 39673
Killing subprocess 39674
Traceback (most recent call last):
  File "/home/user15/anaconda3/envs/occlusion/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user15/anaconda3/envs/occlusion/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user15/anaconda3/envs/occlusion/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/user15/anaconda3/envs/occlusion/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/user15/anaconda3/envs/occlusion/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user15/anaconda3/envs/occlusion/bin/python', '-u', 'main.py', '--local_rank=1', '--config', 'experiments/KINS/pcnet_m/config_train_default_no_rgb.yaml', '--launcher', 'pytorch', '--exp_path', 'experiments/KINS/pcnet_m_default_no_rgb']' returned non-zero exit status 1.

**Comment by Championchess** [comment]
Have you resolved the problem eventually? I am also facing the same issue

**Comment by rukshankr** [comment]
@landian60 could you tell me how you solved the issue?
